### ISSUE TITLE
Backslot drawing sword and putting it away

### ISSUE THREAD

**Issue by fadedwisp** [HollowedWanderer/Combat-Amenities#12] opened 2024-12-11 08:04 UTC
when i draw the sword it goes from my back to my hotbar which is good, but when i use the hotkey to put the sword back using the hotkey again it doesn't want to work

**Comment by HollowedWanderer** [comment] 2024-12-11 14:01
what version of the mod are you using?

**Comment by fadedwisp** [comment] 2024-12-11 15:53
The latest one that was on modrinth

**Comment by HollowedWanderer** [comment] 2024-12-12 01:58
for 1.21, 1.21.1, or 1.20.1?

**Comment by fadedwisp** [comment] 2024-12-12 02:30
1.21.1

**Comment by HollowedWanderer** [comment] 2024-12-12 20:05
is this in multiplayer or singleplayer? Also do you have any other mods installed?

**Comment by fadedwisp** [comment] 2024-12-12 20:10
This is on multiplayer and single player. I have  a custom mod pack with a
keybind encircle to help manage my keys binds. It only works once and then
acts up. I’m using a mod called keybind galore plus

**Comment by HollowedWanderer** [comment] 2024-12-12 21:48
hmm, I tried out the older mod version myself, but I cannot get the issue, it seems like it might just be an issue with the other mods

**Comment by fadedwisp** [comment] 2024-12-12 21:54
The only thing I can assume is it would be the keybinds galore mod. Is
there any other mind that you suggest that can help with buying the six
because I have multiple mods in my server and everyone is complaining about
keybinds

**Comment by fadedwisp** [comment] 2024-12-12 21:55
Sorry I’m using Siri. Is there any other mod you suggest I use for the
keybinds issue?

**Comment by HollowedWanderer** [comment] 2024-12-13 15:14
I don't know, I was just saying that it most likely is a bug caused by the other mods. I can't seem to replicate the problem so I'm going to close the issue

**Closed by HollowedWanderer** 2024-12-13 15:14 UTC
Labels: wontfix, Incompatibility
